# Generated by Django 4.0.2 on 2022-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blogs/'),
        ),
    ]
