# Generated by Django 4.0.2 on 2022-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_height_patient_weight_alter_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, default='patients/user-default.png', max_length=200, null=True, upload_to='patients/'),
        ),
    ]
