# Generated by Django 4.0.2 on 2022-02-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_patient_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(blank=True, default='patient', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
