# Generated by Django 4.0.2 on 2022-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='college',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
