# Generated by Django 5.0.7 on 2024-07-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-votes_ratio']},
        ),
    ]
