# Generated by Django 4.0.2 on 2022-02-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_report_delete_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='patient',
            new_name='adhar',
        ),
    ]
