# Generated by Django 4.0.2 on 2022-02-12 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_rename_patient_report_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.FileField(default='ujj.pdf', upload_to='patient_report/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='adhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
