# Generated by Django 4.0.2 on 2022-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_report_report_alter_report_adhar_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
